[simulation]
mtu = 1500

[interfaces]
tun_a = "tunA"
tun_b = "tunB"

[tun_ingress]
tun_a_ingress = "Rx0y0"
tun_b_ingress = "Rx5y5"

[topology]
# Example: two routers and a link between them
[routers]
Rx0y0 = {}
Rx5y5 = {}

[links]
Rx0y0_Rx5y5 = { delay_ms = 10, jitter_ms = 0, loss_percent = 0, mtu = 1500, bandwidth_mbps = 100 }
