[simulation]
mtu = 1500

[interfaces]
tun_a = "tunA"
tun_b = "tunB"

[tun_ingress]
tun_a_ingress = "Rx0y0"
tun_b_ingress = "Rx5y5"

[topology]
[routers]
Rx0y0 = {}
Rx5y5 = {}

[links]
tunA_Rx0y0 = { delay_ms = 1, loss_percent = 0.0, load_balance = false }
tunB_Rx5y5 = { delay_ms = 1, loss_percent = 0.0, load_balance = false }
Rx0y0_Rx5y5 = { delay_ms = 10, loss_percent = 0.0, load_balance = false }
