[simulation]
mtu = 1500
seed = 42

[interfaces]
tun_a = "tunA"
tun_b = "tunB"

[tun_ingress]
tun_a_ingress = "Rx0y0"
tun_b_ingress = "Rx0y2"

enable_multipath = true

[topology]
[topology.routers]
Rx0y0 = {}
Rx0y1 = {}
Rx0y2 = {}

[topology.links]
Rx0y0_Rx0y1 = { delay_ms = 10, jitter_ms = 0, loss_percent = 0.0, load_balance = true }
Rx0y0_Rx0y2 = { delay_ms = 10, jitter_ms = 0, loss_percent = 0.0, load_balance = true }
